version: '3'

services:

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 5001:9000
    restart: unless-stopped
    networks:
      - proxy

  db:
    image: jc21/mariadb-aria:latest
    container_name: mariadb
    env_file: .env
    environment:
      TZ: '${TIMEZONE}'
      MYSQL_ROOT_PASSWORD: '${ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./nginx/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - proxy

  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: proxymanager
    env_file: .env
    ports:
      - 80:80
      - 5002:81
      - 443:443
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    environment:
      TZ: '${TIMEZONE}'
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "${MYSQL_USER}"
      DB_MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      DB_MYSQL_NAME: "${MYSQL_DATABASE}"
      DISABLE_IPV6: 'true'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - proxy

  dashboard:
    image: b4bz/homer
    container_name: homer
    ports:
      - 5003:8080
    restart: unless-stopped
    env_file: .env
    environment:
      - USER=${USER}
      - GROUP=${USER}
      - UID=${PUID}
      - GID=${PGID}
      - INIT_ASSETS=0
    volumes:
      - ./homer:/www/assets:ro
    networks:
      - proxy

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - 5004:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - proxy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 5005:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - proxy

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - proxy

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - proxy

  speedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    ports:
      - 5006:3000
    restart: unless-stopped
    networks:
      - proxy

  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: ddns-cloudflare
    restart: unless-stopped
    env_file: .env
    environment:
      - API_KEY=${DNSAPI}
      - ZONE=${SITE}
      - PROXIED=true
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - proxy

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 21600
    networks:
      - proxy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    env_file: .env
    ports:
       - 5007:8080
    environment:
       - PUID=${PUID}
       - PGID=${PGID}
       - TZ=${TIMEZONE}
    volumes:
       - ./qbit:/config
       - ./Downloads:/downloads
    restart: unless-stopped
    networks:
      - proxy

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./Jackett:/config
      - ./Downloads:/downloads
    ports:
      - 5008:9117
    restart: unless-stopped
    networks:
      - proxy
    
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./Radarr:/config
      - ./Video/Filmovi:/movies
      - ./Video/Crtani:/cartoons
      - ./Video/Anime/Filmovi:/anime
      - ./Downloads:/downloads
    ports:
      - 5009:7878
    restart: unless-stopped
    networks:
      - proxy
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ./Sonarr:/config
      - ./Video/Serije:/tv
      - ./Video/Anime-serije:/animetv
      - ./Downloads:/downloads
    ports:
      - 5010:8989
    restart: unless-stopped
    networks:
      - proxy

  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    user: "${UID}:${GID}"
    ports:
      - 5011:8080
    volumes:
      - ./:/data
      - ./filebrowser:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy

  code-server:
    image: lscr.io/linuxserver/code-server
    container_name: code-server
    env_file: .env
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - PASSWORD=${MYSQL_PASSWORD} #optional
      - SUDO_PASSWORD=${MYSQL_PASSWORD} #optional
      - PROXY_DOMAIN=code-server.${SITE} #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./code:/config
    ports:
      - 5012:8443
    restart: unless-stopped
    networks:
      - proxy

  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: vpn
    env_file: .env
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - SERVERURL=vpn.${SITE} #optional
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ./wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - proxy

  matomo:
    image: matomo
    ports:
      - 5013:80
    environment:
      - MATOMO_DATABASE_HOST=dbmatomo
      - MATOMO_DATABASE_TABLES_PREFIX=mat_
      - MATOMO_DATABASE_USERNAME=${MYSQL_USER}
      - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MYSQL_DATABASE}
    volumes:
      - ./Matomo:/var/www/html
    links:
      - dbmatomo:dbmatomo
    restart: unless-stopped
    networks:
      - proxy

  dbmatomo:
    image: yobasystems/alpine-mariadb:latest
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./Matomodb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local