# Homepage configuration
# See https://fontawesome.com/icons for icons options

logo: "https://github.com/sekkigit/porfolio.sekiteh/blob/gh-pages/img/seki-logo-simple.png?raw=true"
title: "SekiTEH"
subtitle: "Dashboard"

header: true
footer: false
columns: "3"

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#00c1c1"
    highlight-secondary: "#00c1c9"
    highlight-hover: "#3a3a3a"
    background: "#f8f8f8"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#131313"
    highlight-secondary: "#2b2b2b"
    highlight-hover: "#131314"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Porfolio"
    icon: "fas fa-user-circle"
    url: "https://porfolio.sekiteh.xyz" # static website from GitHub Pages
    target: "_blank" # optional html a tag target attribute
  - name: "Linkedin"
    icon: "far fa-user-circle"
    url: "https://hr.linkedin.com/in/senad-dizdarevic-062269100?trk=people-guest_people_search-card"
    target: "_blank" # optional html a tag target attribute
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/sekkigit"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Apps"
    logo: "https://cdn-icons-png.flaticon.com/512/1055/1055662.png"
    items:
      - name: "Plex"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/plex.png?raw=true"
        subtitle: "Media"
        tag: "Stream"
        url: "https://app.plex.tv/desktop/#!/"
        target: "_blank"
      - name: "FileBrowser"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/filebrowser.png?raw=true"
        subtitle: "Files"
        tag: "File menager"
        url: "https://file.sekiteh.xyz"
        target: "_blank"
      - name: "Code Server"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/vscode.png?raw=true"
        subtitle: "Code space"
        tag: "VSCode"
        url: "https://code-server.sekiteh.xyz"
        target: "_blank"

  - name: "Downloading"
    logo: "https://cdn-icons-png.flaticon.com/512/429/429331.png"
    items:
      - name: "QbitTorrent"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/qbittorrent.png?raw=true"
        subtitle: "Downlaods"
        tag: "Download torrents"
        url: "https://qbit.sekiteh.xyz"
        target: "_blank"
      - name: "Sonarr"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/sonarr.png?raw=true"
        subtitle: "TV RSS"
        tag: "Tv series"
        url: "https://sonarr.sekiteh.xyz"
        target: "_blank"
      - name: "Radarr"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/radarr.png?raw=true"
        subtitle: "Movie RSS"
        tag: "Movies"
        url: "https://radarr.sekiteh.xyz/"
        target: "_blank"
      - name: "Jackett"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/jackett.png?raw=true"
        subtitle: "Indexer"
        tag: "Torrent indexer"
        url: "https://jackett.sekiteh.xyz/"
        target: "_blank"

  - name: "Web-utilitys"
    logo: "https://cdn-icons-png.flaticon.com/512/1043/1043688.png"
    items:
      - name: "Cloudflare"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/cloudflare.png?raw=true"
        subtitle: "DNS"
        url: "https://www.cloudflare.com"
        target: "_blank"
        tag: "web-DNS"
      - name: "Namecheap"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/namecheap.png?raw=true"
        subtitle: "Domains"
        tag: "Domain provider"
        url: "https://www.namecheap.com/myaccount/login/?ReturnUrl=%2f"
        target: "_blank"
      - name: "My IP"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/ip.png?raw=true"
        subtitle: "IP address lookup"
        tag: "What's my IP?"
        url: "https://www.tunnelbear.com/whats-my-ip"
        target: "_blank"

  - name: "Monitor"
    logo: "https://cdn-icons-png.flaticon.com/512/429/429331.png"
    items:
      - name: "Motomo"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/matomo.png?raw=true"
        subtitle: "Analytics"
        url: "https://analytics.sekiteh.xyz"
        target: "_blank"
        tag: "Monitor web traffic"
      - name: "Grafana"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/grafana.png?raw=true"
        subtitle: "Monitoring"
        url: "https://monitor.sekiteh.xyz"
        target: "_blank"
        tag: "Monitor server stats"
      - name: "SpeedTest"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/speedtest.png?raw=true"
        subtitle: "Connection Speed"
        tag: "Internet Speed test"
        url: "https://speed.sekiteh.xyz/"
        target: "_blank"

  - name: "Admin"
    logo: "https://www.pngmart.com/files/21/Admin-Profile-Vector-PNG-Clipart.png"
    items:
      - name: "Nginx Proxy Menager"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/nginxproxymanager.png?raw=true"
        subtitle: "Proxy"
        tag: "Proxy menager"
        url: "https://nginx.sekiteh.xyz"
        target: "_blank"
      - name: "Portainer"
        logo: "https://github.com/sekkigit/Media-server/blob/main/icons/portainer.png?raw=true"
        subtitle: "Docker"
        tag: "Docker menager"
        url: "https://dock.sekiteh.xyz"
        target: "_blank"